# Generated by Django 4.2.1 on 2023-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/'),
        ),
    ]
