# Generated by Django 4.2.1 on 2023-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumb_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
